### ISSUE TITLE
Problems ,when  trying to install it on linux gentoo , custom blocks for GnuRadio 3.10.4.0  (from  AIS Simulator).

### ISSUE THREAD

**Issue by Brumi-2021** [Mictronics/ais-simulator#4]
Hi, I am very interesting to install that  AIS-SIMULATOR, 

 I am running  pentoo distro , (gentoo linux including a vaste  of excellent packages ) 

* Currently my main related installation is the following one : 
*  python --version ==> Python 3.10.8
*  kernel version , ==> linux-6.0.9-pentoo
*  GNU Radio Companion ==>  ,3.10.4.0 (Python 3.10.8)

Trying to install your specific AISTX  blocks i tried to follow your instructions , changing  python 3.8 -> 3.10, and almost all worked well 
except that part : 

> CMake Error at swig/CMakeLists.txt:37 (include):
>   include could not find requested file:
> 
>     GrSwig
> 
> CMake Error at swig/CMakeLists.txt:51 (GR_SWIG_MAKE):
>   Unknown CMake command "GR_SWIG_MAKE".
> 

Just in case, let  me share below , the full command and display echo , 

Any help or clue would be appreciated ! 
thanks in advance , 
Cheers, 

.----------------------------------------------

pentoo@pentoo ~/Documents/ais-simulator-master/gr-ais_simulator/build $ cmake ../ -Wno-dev -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.10 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.10.so

-- The CXX compiler identification is GNU 11.3.0
-- The C compiler identification is GNU 11.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not specified: defaulting to release.
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
-- Checking for module 'gmp'
--   Found gmp, version 6.2.1
-- Found GMP: /usr/lib64/libgmpxx.so  
-- Using GMP.
-- Found MPLIB: /usr/lib64/libgmpxx.so  
-- Found Boost: /usr/lib64/cmake/Boost-1.80.0/BoostConfig.cmake (found suitable version "1.80.0", minimum required is "1.79.0") found components: date_time program_options system regex thread 
-- Found Volk: Volk::volk  
-- User set python executable /usr/bin/python3.10
-- Found PythonInterp: /usr/bin/python3.10 (found version "3.10.8") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.10.so (found suitable exact version "3.10.8") 
-- Found Git: /usr/bin/git  
-- Found Doxygen: /usr/bin/doxygen (found version "1.9.5") found components: doxygen dot 
-- Using install prefix: /usr/local
-- Building for version: v1.0-compat-xxx-xunknown / 1.0.0git
-- No C++ unit tests... skipping
-- Found SWIG: /usr/bin/swig (found version "4.0.2")  
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.10.so (found version "3.10.8") 

> CMake Error at swig/CMakeLists.txt:37 (include):
>   include could not find requested file:
>     GrSwig
> 
> CMake Error at swig/CMakeLists.txt:51 (GR_SWIG_MAKE):
>   Unknown CMake command "GR_SWIG_MAKE".

-- Configuring incomplete, errors occurred!
See also "/home/pentoo/Documents/ais-simulator-master/gr-ais_simulator/build/CMakeFiles/CMakeOutput.log".

**Comment by Mictronics** [comment]
Solved with PR #5.
